### ISSUE TITLE
BUG: Inconsistent paths for optimizer

### ISSUE THREAD

**Issue by buthed010203** [EZCampusDevs/frontend#13]
The optimizer is set to display on `/optimize` yet the *Tools* header leads to `/optimizer`. 
https://github.com/EZCampusDevs/frontend/blob/f04cffbfa11e6225e078ce5093171a8331389590/frontend/client/src/App.js#L65
https://github.com/EZCampusDevs/frontend/blob/f04cffbfa11e6225e078ce5093171a8331389590/frontend/client/src/components/navbar/PageHeader.js#L67

Edit: This should probably be its own issue but the optimizer page doesn't seem to work either.

**Comment by jasonmzx** [comment]
Thanks for noticing, we'll fix this upon completion of the navbar revamp!
