### ISSUE TITLE
BUG: Discord Link Invalid

### ISSUE THREAD

**Issue by buthed010203** [EZCampusDevs/frontend#8]
The discord link on the about us page has expired:
https://github.com/EZCampusDevs/frontend/blob/c09862af6fd81ca5276f9694a860365edcd230f0/frontend/client/src/pages/AboutUsPage.js#L75

**Comment by danielljeon** [comment]
Hi @buthed010203. A little embarrassing, but I disabled that invite link as we closed the server for only internal team use. I didn't get a chance to update the code at the time. If you're interested in joining our team or want to find out more about EZCampus, feel free to reach out on discord @`borkd`.

Given the referenced AboutUs page is no longer on our current build I am closing this issue.
